server:
  address: localhost
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tododb?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: lee020317

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    generate_ddl: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace